version: "3.9"
services: 
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
  postgres:
    image: 'postgres:latest'
    platform: linux/arm64
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restDB
      PGDATA: /var/lib/postgresql/data/data/
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  service:
    build: ./service
    ports: 
      - 50050:50050
    depends_on: 
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restDB
    restart: always
  rest-api:
    build: ./rest-api
    ports:
      - "3000:3000"
    restart: always
  angular:
    build: ./angular
    ports:
      - "9000:80"
    environment:
      ADDRESS : rest-api:3000
  
volumes: 
  data:
