// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package postgres

import (
	"encoding/json"
)

type Registration struct {
	NumberPlate string
	Vehicle     json.RawMessage
	Insurer     json.RawMessage
}
